import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useRouter } from 'next/router'

import styles from '../../styles/Index.module.css'
import Navigation from '../../components/Navigation'
import Hero from '../../components/Hero'

import fs from 'fs'
import matter from 'gray-matter'
import md from 'markdown-it'
import { TbArrowLeft } from 'react-icons/tb'


export async function getStaticPaths(){
    const files = fs.readdirSync('posts')
    const paths = files.map((fileName) => {
        const slug = fileName.replace('.md', '');
        return {
        params: {slug}
        }
    })
    return {
        paths,
        fallback: false
    }
}

export async function getStaticProps({ params: { slug} }) {
    const fileName = fs.readFileSync(`posts/${slug}.md`, 'utf-8');
    const { data: frontmatter, content } = matter(fileName);
    return {
        props: {
            frontmatter,
            content
        }
    }
}

export default function PostPage({ frontmatter, content }) {
    const title = `Jordan Blewer / ${frontmatter.title}`
    const Router = useRouter()
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
                        <div>
                            <div className={styles.header}>
                                <h3 className={styles.heading}>{frontmatter.title}</h3>
                                <a className={styles.flex+ ' ' + styles.link} onClick={() => Router.back()}><TbArrowLeft className={styles.icon} />
                                <p>Go Back</p></a>
                            </div>
                            <div dangerouslySetInnerHTML={{ __html: md().render(content) }} />
                        </div>
        </>
    )
}