import fs from 'fs'
import matter from 'gray-matter'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../../styles/Index.module.css'
import Navigation from '../../components/Navigation'
import Hero from '../../components/Hero'

import md from 'markdown-it'
import { TbArrowLeft } from 'react-icons/tb'

export async function getStaticPaths(){
    const files = fs.readdirSync('posts')
    const paths = files.map((fileName) => {
        const slug = fileName.replace('.md', '');
        return {
        params: {slug}
        }
    })
    return {
        paths,
        fallback: false
    }
}

export async function getStaticProps({ params: { slug} }) {
    const fileName = fs.readFileSync(`posts/${slug}.md`, 'utf-8');
    const { data: frontmatter, content } = matter(fileName);
    return {
        props: {
            frontmatter,
            content
        }
    }
}

export default function PostPage({ frontmatter, content }) {

    console.log(frontmatter.title)
    const title = `Jordan Blewer / ${frontmatter.title}`
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <main>
                <div className={styles.container}>
                <Navigation />
                <Hero />
                    <div>
                    <div className={styles.header}>
                        <h2 className={styles.heading}>{frontmatter.title}</h2>
                        <Link className={styles.flex+ ' ' + styles.link} href='/work'><TbArrowLeft className={styles.icon} />
                        <h3>Go Back</h3></Link>
                    </div>
                        <div dangerouslySetInnerHTML={{ __html: md().render(content) }} />
                    </div>
                </div>
            </main>
        </>
    )
}