import Head from 'next/head'
import styles from '../styles/Index.module.css'
import Navigation from '../components/Navigation'
import Hero from '../components/Hero'
import SelectedWork from '../components/SelectedWork'

export default function Home() {
  return (
    <>
      <Head>
        <title>Jordan Blewer / Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
        <SelectedWork />
    </>
  )
}
