import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Index.module.css'
import Navigation from '../components/Navigation'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Jordan Blewer / Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class={styles.container}>
        <Navigation />
        <Hero />
      </main>
    </>
  )
}
