import Head from 'next/head'
import styles from '../styles/Index.module.css'
import Navigation from '../components/Navigation'
import Hero from '../components/Hero'
import ProfileMain from '../components/ProfileMain'

export default function Profile() {
  return (
    <>
      <Head>
        <title>Jordan Blewer / Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={styles.container}>
        <Navigation />
        <Hero />
        <ProfileMain />
      </main>
    </>
  )
}
