import Head from 'next/head'
import fs from 'fs'
import matter from 'gray-matter'

import styles from '../styles/Index.module.css'
import Navigation from '../components/Navigation'
import Hero from '../components/Hero'
import LatestWork from '../components/LatestWork'
import Project from '../components/Project'

export async function getStaticProps() {
  const files = fs.readdirSync('posts')
  const posts = files.map((fileName) => {
    const slug = fileName.replace('.md', '');
    const readFile = fs.readFileSync(`posts/${fileName}`, 'utf-8');
    const { data: frontmatter } = matter(readFile);

    return {
      slug,
      frontmatter,
    };
});

return {
    props: {
      posts,
    },
}};

export default function Work({posts}) {
  return (
    <>
      <Head>
        <title>Jordan Blewer / Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={styles.container}>
        <Navigation />
        <Hero />
        <LatestWork />
        {posts?.map(({slug, frontmatter}) => (
          <Project key={slug} slug={slug} title={frontmatter.title} summary={frontmatter.summary} img={frontmatter.img}/>
        ))}
      </main>
    </>
  )
}
